apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: viajiamos
  labels:
    app: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: http
      port: 8002
      targetPort: http