apiVersion: v1
kind: Service
metadata:
  name: realtime-service
  namespace: viajiamos
  labels:
    app: realtime-service
spec:
  type: ClusterIP
  selector:
    app: realtime-service
  ports:
    - name: http
      port: 8004
      targetPort: http